#!/usr/bin/env python2
# (c) Copyright 2014 Josh Wright
import subprocess
import os
import sys
from tempfile import TemporaryFile

indexFile = "/home/j0sh/Documents/git/FileFind/index"
historyFile = "/home/j0sh/Documents/git/FileFind/test"
class main(object):
	lineHeight = str(30)
	exclude = ("/mnt/home/j0sh/.config/",
		"/mnt/home/j0sh/.PlayOnLinux/",
		"/mnt/home/j0sh/.cache/",
		"/mnt/home/j0sh/.mozilla/",
		"/mnt/home/j0sh/.local/share/Steam/",
		"/mnt/home/j0sh/.xbmc/",
		"/home/j0sh/Data-btrfs/.systemfiles/")
	customLines = {'fixmouse':'xinput set-button-map "Logitech Unifying Device. Wireless PID:4013" 1 2 1 4 5 3 3 3 3 3 3;xinput set-button-map "USB Optical Wheel Mouse" 3 2 1 4 5 3 3 3 3 3 3;xinput --set-prop 10 "Device Accel Adaptive Deceleration" 2'}
	def __init__(self,historyFile,doIndex,indexFile,doInteractive=True):
		self.historyFile = historyFile
		self.indexFile = indexFile
		self.readHistory()
		if doIndex:
			self.makeIndex()
			self.writeIndex()
		else:
			self.readIndex()
		if doInteractive:
			self.mainLoop()
			self.writeHistory()
	def readHistory(self):
		with open(self.historyFile,'r') as importFile:
			self.history = eval(importFile.read())
	def writeHistory(self):
		with open(self.historyFile,'w') as exportFile:
			exportFile.write( str( self.history ).replace(',',',\n') )
	def readIndex(self):
		self.fileList = []
		with open(self.indexFile,'r') as importFile:
			for line in importFile.read().split('\n'):
				self.fileList.append(line)
	def writeIndex(self):
		with open(self.indexFile,'w') as exportFile:
			for line in self.fileList:
				exportFile.write(line+'\n')
	def doHistoryReOrdering(self):
		historyList = sorted(self.history,key=self.history.get)
		for line in historyList[::-1]:
			if line in self.fileList:
				self.fileList.remove(line)
				self.fileList.insert(0,line)
	def makeIndex(self):
		self.fileList = []
		# home
		for line in subprocess.check_output(["find", "/mnt/home" ]).split("\n"):
			if not line.startswith(self.exclude):
				self.fileList.append(line[4:])
		# Data-btrfs
		for line in subprocess.check_output(["locate", "/home/j0sh/Data-btrfs/" ]).split("\n"):
			if not line.startswith(self.exclude):
				self.fileList.append(line)
		# extra
		self.fileList.extend(self.customLines)
		self.doHistoryReOrdering()
	def handleSelection(self,selection):
		if selection in self.customLines:
			os.system(self.customLines[selection])
		else:
			os.system("xdg-open "+"'"+selection+"'")
	def mainLoop(self):
		with TemporaryFile() as fileListFile:
			fileListFile.write('\n'.join(self.fileList))
			fileListFile.seek(0)
			try:
				selection = subprocess.check_output(["dmenu", "-i", "-l", self.lineHeight, "-fn", "DejaVu Sans Mono-11", "-nb", "#000" ],stdin=fileListFile)
				selection = selection.strip('\n')
				if not selection in self.fileList:
					exit()
				self.handleSelection(selection)
				# os.system("xdg-open "+"'"+selection+"'")
			except:
				selection = ''
		if selection in self.history:
			self.history[selection] += 1
		else:
			if selection != '':
				self.history[selection] = 1
if sys.argv[-1] == "IndexOnly":
	mainClass = main(historyFile,True,indexFile,doInteractive=False)
else:
	mainClass = main(historyFile,False,indexFile)